from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.invoice import Invoice
from app.routes.invoice import get_current_user
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.colors import HexColor, white, black
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import mm
import io

router = APIRouter(tags=["PDF"])

@router.get("/invoices/{invoice_id}/pdf")
def generate_pdf(invoice_id: str, current_user=Depends(get_current_user), db: Session = Depends(get_db)):
    invoice = db.query(Invoice).filter(Invoice.id == invoice_id, Invoice.user_id == current_user.id).first()
    if not invoice:
        raise HTTPException(status_code=404, detail="Invoice not found")

    is_german = invoice.currency == "EUR"
    tax_label = "MwSt (19%)" if is_german else "GST (18%)"
    currency_symbol = "€" if is_german else "₹"

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=20*mm, leftMargin=20*mm, topMargin=20*mm, bottomMargin=20*mm)

    styles = getSampleStyleSheet()
    indigo = HexColor("#6366f1")
    dark = HexColor("#1a1a2e")
    gray = HexColor("#666666")

    elements = []

    # Header
    elements.append(Paragraph('<font color="#6366f1" size="22"><b>InvoAutomate</b></font>', styles["Normal"]))
    elements.append(Spacer(1, 5*mm))
    elements.append(Paragraph(f'<font size="18"><b>INVOICE</b></font>', styles["Normal"]))
    elements.append(Paragraph(f'<font color="#6366f1">{invoice.invoice_number}</font>', styles["Normal"]))
    elements.append(Spacer(1, 8*mm))

    # Client Info
    elements.append(Paragraph('<font color="#666666" size="9">BILL TO</font>', styles["Normal"]))
    elements.append(Paragraph(f'<b>{invoice.client_name}</b>', styles["Normal"]))
    elements.append(Paragraph(f'{invoice.client_email or ""}', styles["Normal"]))
    elements.append(Spacer(1, 8*mm))

    # Items Table
    table_data = [["Description", "Qty", "Unit Price", "Total"]]
    if invoice.items:
        for item in invoice.items:
            name = item.get("name", item.get("description", "Service"))
            qty = item.get("quantity", 1)
            price = item.get("price", 0)
            total = qty * price
            table_data.append([name, str(qty), f"{currency_symbol}{price:,.2f}", f"{currency_symbol}{total:,.2f}"])
    else:
        table_data.append(["Services", "1", f"{currency_symbol}{invoice.subtotal:,.2f}", f"{currency_symbol}{invoice.subtotal:,.2f}"])

    table = Table(table_data, colWidths=[90*mm, 20*mm, 35*mm, 35*mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), indigo),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#f9fafb"), white]),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#e5e7eb")),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 8*mm))

    # Totals
    totals_data = [
        ["Subtotal:", f"{currency_symbol}{invoice.subtotal:,.2f}"],
        [f"{tax_label}:", f"{currency_symbol}{invoice.tax_amount:,.2f}"],
        ["Total:", f"{currency_symbol}{invoice.total:,.2f}"],
    ]
    totals_table = Table(totals_data, colWidths=[120*mm, 40*mm], hAlign="RIGHT")
    totals_table.setStyle(TableStyle([
        ("FONTNAME", (0, 2), (-1, 2), "Helvetica-Bold"),
        ("FONTSIZE", (0, 2), (-1, 2), 12),
        ("TEXTCOLOR", (0, 2), (-1, 2), indigo),
        ("LINEABOVE", (0, 2), (-1, 2), 1, indigo),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
    ]))
    elements.append(totals_table)
    elements.append(Spacer(1, 15*mm))

    # Footer
    footer_text = "Gemäß §14 UStG — MwSt compliant invoice" if is_german else "GST Compliant Invoice — Generated by InvoAutomate"
    elements.append(Paragraph(f'<font color="#999999" size="8">{footer_text}</font>', styles["Normal"]))

    doc.build(elements)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={invoice.invoice_number}.pdf"}
    )
